//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartH2O_SeeApp.StatsService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="StatsService.SmartH20Service")]
    public interface SmartH20Service {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SmartH20Service/GetHourlyInSpecificDayParameter", ReplyAction="http://tempuri.org/SmartH20Service/GetHourlyInSpecificDayParameterResponse")]
        string GetHourlyInSpecificDayParameter(string year, string month, string day, string parameter);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SmartH20Service/GetHourlyInSpecificDayParameter", ReplyAction="http://tempuri.org/SmartH20Service/GetHourlyInSpecificDayParameterResponse")]
        System.Threading.Tasks.Task<string> GetHourlyInSpecificDayParameterAsync(string year, string month, string day, string parameter);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SmartH20Service/GetDailyInThresholdParameter", ReplyAction="http://tempuri.org/SmartH20Service/GetDailyInThresholdParameterResponse")]
        string GetDailyInThresholdParameter(string firstYear, string firstMonth, string firstDay, string secondYear, string secondMonth, string secondDay, string parameter);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SmartH20Service/GetDailyInThresholdParameter", ReplyAction="http://tempuri.org/SmartH20Service/GetDailyInThresholdParameterResponse")]
        System.Threading.Tasks.Task<string> GetDailyInThresholdParameterAsync(string firstYear, string firstMonth, string firstDay, string secondYear, string secondMonth, string secondDay, string parameter);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SmartH20Service/GetDailyAlarm", ReplyAction="http://tempuri.org/SmartH20Service/GetDailyAlarmResponse")]
        string GetDailyAlarm(string year, string month, string day);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SmartH20Service/GetDailyAlarm", ReplyAction="http://tempuri.org/SmartH20Service/GetDailyAlarmResponse")]
        System.Threading.Tasks.Task<string> GetDailyAlarmAsync(string year, string month, string day);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SmartH20Service/GetThresholdAlarm", ReplyAction="http://tempuri.org/SmartH20Service/GetThresholdAlarmResponse")]
        string GetThresholdAlarm(string firstYear, string firstMonth, string firstDay, string secondYear, string secondMonth, string secondDay);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SmartH20Service/GetThresholdAlarm", ReplyAction="http://tempuri.org/SmartH20Service/GetThresholdAlarmResponse")]
        System.Threading.Tasks.Task<string> GetThresholdAlarmAsync(string firstYear, string firstMonth, string firstDay, string secondYear, string secondMonth, string secondDay);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SmartH20ServiceChannel : SmartH2O_SeeApp.StatsService.SmartH20Service, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SmartH20ServiceClient : System.ServiceModel.ClientBase<SmartH2O_SeeApp.StatsService.SmartH20Service>, SmartH2O_SeeApp.StatsService.SmartH20Service {
        
        public SmartH20ServiceClient() {
        }
        
        public SmartH20ServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SmartH20ServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SmartH20ServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SmartH20ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetHourlyInSpecificDayParameter(string year, string month, string day, string parameter) {
            return base.Channel.GetHourlyInSpecificDayParameter(year, month, day, parameter);
        }
        
        public System.Threading.Tasks.Task<string> GetHourlyInSpecificDayParameterAsync(string year, string month, string day, string parameter) {
            return base.Channel.GetHourlyInSpecificDayParameterAsync(year, month, day, parameter);
        }
        
        public string GetDailyInThresholdParameter(string firstYear, string firstMonth, string firstDay, string secondYear, string secondMonth, string secondDay, string parameter) {
            return base.Channel.GetDailyInThresholdParameter(firstYear, firstMonth, firstDay, secondYear, secondMonth, secondDay, parameter);
        }
        
        public System.Threading.Tasks.Task<string> GetDailyInThresholdParameterAsync(string firstYear, string firstMonth, string firstDay, string secondYear, string secondMonth, string secondDay, string parameter) {
            return base.Channel.GetDailyInThresholdParameterAsync(firstYear, firstMonth, firstDay, secondYear, secondMonth, secondDay, parameter);
        }
        
        public string GetDailyAlarm(string year, string month, string day) {
            return base.Channel.GetDailyAlarm(year, month, day);
        }
        
        public System.Threading.Tasks.Task<string> GetDailyAlarmAsync(string year, string month, string day) {
            return base.Channel.GetDailyAlarmAsync(year, month, day);
        }
        
        public string GetThresholdAlarm(string firstYear, string firstMonth, string firstDay, string secondYear, string secondMonth, string secondDay) {
            return base.Channel.GetThresholdAlarm(firstYear, firstMonth, firstDay, secondYear, secondMonth, secondDay);
        }
        
        public System.Threading.Tasks.Task<string> GetThresholdAlarmAsync(string firstYear, string firstMonth, string firstDay, string secondYear, string secondMonth, string secondDay) {
            return base.Channel.GetThresholdAlarmAsync(firstYear, firstMonth, firstDay, secondYear, secondMonth, secondDay);
        }
    }
}
